name: Build and deploy to gh-pages

on: push

jobs:
  deploy:
    name: Build and deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm build
      - uses: JamesIves/github-pages-deploy-action@4
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: dist
