name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy to gh-pages
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
